[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.format]
quote-style = "single"
line-ending = "lf"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403", "I001"]